### ISSUE TITLE
CORS error in FF using apify-client

### ISSUE THREAD

**Issue by azmartone** [apifytech/apify-client-js#123]
Hey guys, I’m getting a cors error in FF and IE, but not Chrome. How do I start to resolve this? Thanks.

I’m using the apify-client

passing user-id and passing dataset-id
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.apify.com/v2/datasets/[task id]/items. (Reason: missing token ‘user-agent’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.apify.com/v2/datasets/[task id]/items. (Reason: CORS request did not succeed).

**Comment by mtrunkat** [comment]
Thank you for reporting this. We will update our CORS configuration to allow this header that is automatically added by the API client.

**Comment by mtrunkat** [comment]
We have just deployed a new version of our API removing this restriction. So everything should now work correctly for you.

**Comment by azmartone** [comment]
I tried it this morning and still run into the issue. Maybe the API changes need to propagate?

**Comment by mtrunkat** [comment]
Could you pass response headers you receive? We are now allowing all the headers as you can see here: https://take.ms/NuZPW

**Comment by mtrunkat** [comment]
Problem is fixed now. Firefox doesn't support wildcards for allowed headers so we whitelisted User-Agent one that was causing the problem.
