### ISSUE TITLE
Code coverage generation not working

### ISSUE THREAD

**Issue by lubos-turek** [apifytech/apify-client-js#14]
```
$ npm run test-cov
...
No coverage information was collected, exit without writing coverage information
```
It's has not worked since the beginning, so it's not a bug we introduced.

Honestly, it's kind of weird:

the `test-cov` script is `npm run build && babel-node node_modules/isparta/bin/isparta cover --report html --report text node_modules/.bin/_mocha`, which does not work.

However, if i switch `node_modules/.bin/_mocha` for my globally installed `_mocha`, it works perfectly. The version is the same, so I reckon it has something to do with relative paths.

**Comment by mtrunkat** [comment]
Done
