### ISSUE TITLE
Listing method's 'desc' parameter wants boolean, but in docs (and API) 1 is used

### ISSUE THREAD

**Issue by metalwarrior665** [apifytech/apify-client-js#71]
When I try for example 
```Apify.client.acts.listRuns({token: process.env.APIFY_TOKEN, actId:'R3z9XMngjgjhzgXMzK', desc: 1})```

The code throws that it expects 'desc 'to be Maybe Boolean. In all listing methods in docs is 'desc: 1' .

**Comment by mtrunkat** [comment]
Fixed.
