### ISSUE TITLE
datasets.getItems() doesn't use exponential backoff on invalid JSON

### ISSUE THREAD

**Issue by jancurn** [apifytech/apify-client-js#92]
IMHO this call should be retried too, similarly as the 500 errors from server.

```
2018-12-20T01:15:10.899Z SyntaxError: Unexpected end of JSON input
2018-12-20T01:15:10.901Z     at JSON.parse (<anonymous>)
2018-12-20T01:15:10.902Z     at exports.parseBody (/usr/src/app/node_modules/apify-client/build/utils.js:247:25)
2018-12-20T01:15:10.903Z     at parseResponse (/usr/src/app/node_modules/apify-client/build/datasets.js:322:79)
2018-12-20T01:15:10.905Z     at <anonymous>
2018-12-20T01:15:10.907Z     at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by mtrunkat** [comment]
All the calls are retried. The problem is here that the call succeeds, the response is passed to body parser and body parser tries to parse it as a JSON. So we need to move exponential backoff one level up from request method to somewhere above body parser and other postprocessing functions.

**Comment by jancurn** [comment]
Hm, good point. Isn't there some other way to figure out the HTTP response did not complete? If there was, we'd just need to throw the right error at the right time.

**Comment by mtrunkat** [comment]
We could create a generic function in `apify-shared` something like

```javascript
const output = await retryWithExponentialBackOff({
  expBackoffMillis: 500,
  expBackoffMaxRepeats: 5,
  func: async () => {
    // here you do the work you want to retry on error
    return output;
  },
})
```

I think that we should not retry on any error but maybe create `RetriableError` for that case.

**Comment by jancurn** [comment]
Sounds like a good idea, to separate the backoff logic with the actual code. `RetryableError` should store the master exception, so that the function can rethrow it after all retries failed.

**Comment by petrpatek** [comment]
How the function could possibly look like: 
```javascript
const retryWithExpBackoff = async (params = {}) => {
    const innerRetry = async (input) => {
        const { func, expBackoffMillis, expBackoffMaxRepeats, retryCount = 0, resolve, reject } = input;
        try {
            const result = await func();
            resolve(result);
        } catch (e) {
            if (retryCount < expBackoffMaxRepeats) {
                console.log(`retrying due to ${e.message}`);
                setTimeout(() => innerRetry({
                    func,
                    expBackoffMillis: expBackoffMillis * 2,
                    expBackoffMaxRepeats,
                    retryCount: retryCount + 1,
                    resolve,
                    reject,
                }), expBackoffMillis);
            } else {
                reject(e);
            }
        }
    };
    return new Promise((resolve, reject) => {
        innerRetry({ ...params, reject, resolve });
    });
};
```
Of course I need to add some params validation and default values. I am just wondering how the logic could be improved.

**Comment by jancurn** [comment]
The exponential backoff should add some randomness into the wait, otherwise the retries of many errors will be consistently retried at the same time. See https://github.com/apifytech/apify-client-js/blob/master/src/utils.js or https://en.wikipedia.org/wiki/Exponential_backoff#Example_exponential_backoff_algorithm 

Also, we should not retry all errors, so we need the `RetryableError` or some `error.retryable` field.

Plus some unit test :)

**Comment by mtrunkat** [comment]
Also check `requestPromise` function in https://github.com/apifytech/apify-client-js/blob/master/src/utils.js#L93

It uses exponential backoff done using while+async/await with randomized wait, etc.

After we implement `retryWithExpBackoff()`  we could use it here also to simplify this promisified request.

**Comment by petrpatek** [comment]
So I rewrite the function to while and async, await. Now it retries only retryable error and the timeout is also randomised. 
```javascript
const retryWithExpBackoff = async (params = {}) => {
    const { func, expBackoffMillis, expBackoffMaxRepeats } = params;
    let iteration = 0;
    while (iteration <= expBackoffMaxRepeats) {
        let result;
        let error;

        try {
            result = await func();
        } catch (e) {
            error = e;
        }

        if (result) {
            return result;
        }

        if (error instanceof RetryableError) {
            const waitMillis = expBackoffMillis * (2 ** iteration);
            const randomizedWaitMillis = _.random(waitMillis, waitMillis * 2);
            if (iteration === Math.round(expBackoffMaxRepeats / 2)) {
                log.warning(`Retry failed ${iteration} times and will be repeated in ${randomizedWaitMillis}ms`, error);
            }
            iteration += 1;

            await new Promise(resolve => setTimeout(resolve, randomizedWaitMillis));
        } else {
            throw error;
        }

        if (iteration >= expBackoffMaxRepeats) {
            throw error;
        }
    }
};

```

**Comment by mtrunkat** [comment]
Done.
