### ISSUE TITLE
runTask - body doesn't work

### ISSUE THREAD

**Issue by metalwarrior665** [apifytech/apify-client-js#97]
Passing body into runTask in client doesn't work 
https://my.apify.com/actors/Pvnv43naYSDNMAGCr#/source

**Comment by metalwarrior665** [comment]
Work with adding `contentType: 'application/json'`

**Comment by mtrunkat** [comment]
We should either make `contentType` obligatory parameter or set default to `application/json`. As we want to support only JSONs for actor tasks the latter one makes sense.

**Comment by jancurn** [comment]
Maybe if `body` is object then we can automatically JSON stringify and if it's text, we'll require `contentType`. This is how `Apify.setValue()` works.

**Comment by mtrunkat** [comment]
But we do this stringification in SDK only. We should not be doing automagic like this in API client.

**Comment by jancurn** [comment]
Good point, the client should be just a thin layer over the API.

**Comment by mtrunkat** [comment]
And main reason why Lukas faced this is https://github.com/apifytech/apify-js/issues/239 , I have just added priority label to that task

**Comment by mtrunkat** [comment]
apifytech/apify-js#239 is done so I am closing this.
